use_frameworks!

platform :ios, '10.0'

target 'DYLameHelper_Example' do
  pod 'DYLameHelper', :path => '../'

  target 'DYLameHelper_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        config.build_settings["VALID_ARCHS"] = "arm64 arm64e x86_64 i386"
      else
        config.build_settings["VALID_ARCHS"] = "arm64 ARM64e"
      #config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end
